[phases.install]
cmds = ["composer install --ignore-platform-reqs --no-dev --prefer-dist --no-interaction --optimize-autoloader"]

[start]
cmd = "php -d display_errors=0 -d display_startup_errors=0 -d error_reporting=0 -S 0.0.0.0:$PORT -t public public/router.php"


