[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:3000 -t public public/index.php"