[phases.setup]
nixPkgs = ["php74", "php74Packages.composer"]

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:3000 -t public public/index.php"
